// Code generated by protoc-gen-go-j5. DO NOT EDIT.
// No J5 Methods, this is a j5 schema package

package date_j5t

import (
	proto "google.golang.org/protobuf/proto"
)

func (msg *Date) Clone() any {
	return proto.Clone(msg).(*Date)
}
